---
title: "Organoid drug response and survival"
author: "Daniel Skubleny"
date: "07/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Load data
```{r}
urlfile<- 'https://raw.githubusercontent.com/skubleny/Integrated-Molecular-Classification-GC/main/Data/combo_nanostring_no67.csv'
combo_nanostring_organoid <-read.csv(urlfile)
combo_nanostring_organoid = combo_nanostring_organoid[,-1]
combo_nanostring_organoid = dplyr::filter(combo_nanostring_organoid, tissue=="organoid" )
combo_nanostring_organoid = combo_nanostring_organoid[-9,] #Remove 64 duplicate


urlfile <- "https://raw.githubusercontent.com/skubleny/Integrated-Molecular-Classification-GC/main/Data/DSS_final.csv"
DSS <-read.csv(urlfile)
DSS = DSS[,-1]

combo_nanostring_organoid = cbind(combo_nanostring_organoid,DSS )
```

#DSS and survival facet
```{r}

combo_nanostring_organoid_long = combo_nanostring_organoid
combo_nanostring_organoid_long = dplyr::select(combo_nanostring_organoid_long, c("sample_id", "DSS_3", "IC50", "STAD_CIN", "STAD_EBV","STAD_GS","STAD_MSI","High_cal"))

combo_nanostring_organoid_long = reshape2::melt(combo_nanostring_organoid_long, id.vars=c("sample_id", "DSS_3", "IC50"))

levels(combo_nanostring_organoid_long$variable) <- c("TCGA CIN", "TCGA EBV","TCGA GS", "TCGA MSI","TME High")

dss_subtype = combo_nanostring_organoid_long %>%
  ggplot(aes(x = DSS_3, y=value,  fill=sample_id)) +
    geom_point(shape=21, colour= "black", size=4.5) + 
    xlim(20,62) +
    scale_y_continuous(limits = c(0,1.2), breaks = c(0.00,0.25,0.50,0.75,1.00))+
    stat_cor(inherit.aes=FALSE,
                  method="pearson", 
                  label.x = 20,
                  label.y = 1.1,
                  aes(x = DSS_3, y =value),
                  cor.coef.name = "R",
                  size = 5.5,
                  r.digits = 2,
                  p.digits = 2) + 
  geom_smooth(inherit.aes=FALSE, aes(x = DSS_3, y=value), method="lm", se=FALSE, colour="black",size=1.5 )+ 
  ylab("Subtype Probability") +
  xlab("Drug Sensitivity Score") +
        theme_bw() +
  theme(axis.text.x = element_text(colour="black", size = 20)) +
  theme(axis.text.y = element_text(colour="black",size = 20)) + 
  theme(plot.title = element_text(colour="black", size=20,hjust = 0, vjust=0)) +
  theme(axis.title.x = element_text(colour="black", size =21, vjust = 0.05)) +
  theme(axis.title.y = element_text(colour="black", size=21)) +
  theme(strip.background =element_rect(fill="white"),
        strip.text = element_text(size=18)) +
  theme(legend.title =element_blank(),
        legend.position="none")+
  facet_grid(~variable, scales="free_x")

ggsave("dss_subtype_final.svg", dss_subtype, width=12, height=4)


```



