---
title: "KOSIN"
author: "Daniel Skubleny"
date: "10/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
#Kosin (Kosin University College of Medicine) Data
data_kosin = getGEO('GSE26901')
```
```{r}
edata_kosin = as.data.frame(data_kosin[["GSE26901_series_matrix.txt.gz"]]@assayData[["exprs"]])  
pheno_kosin = as.data.frame(data_kosin[["GSE26901_series_matrix.txt.gz"]]@phenoData@data)
fdata_kosin = as.data.frame(data_kosin[["GSE26901_series_matrix.txt.gz"]]@featureData@data)
```

#Annotate 
```{r}
edata_kosin = tibble::rownames_to_column(edata_kosin, "ID")
fdata_kosinsubset = dplyr::select(fdata_kosin, c("ID","Entrez_Gene_ID"))
edata_kosin = merge(fdata_KUGHsubset,edata_kosin, by.x="ID")
```
```{r}
annotatedkosin = AnnotationDbi::select(org.Hs.eg.db,keys = as.character(fdata_kosin$Entrez_Gene_ID), columns = c("SYMBOL","ENTREZID","ENSEMBL"), keytype = "ENTREZID")
```
```{r}
edata_kosin = dplyr::select(edata_kosin, c(-"ID")) #Remove ID column 
colnames(edata_kosin)[which(names(edata_kosin) == "Entrez_Gene_ID")] <- "ENTREZID" #Convert column name
```
```{r}
dim(annotatedkosin)
dim(edata_kosin)
table(duplicated(edata_kosin$ENTREZID))
#Because there is duplicates in my target column my merge will not work properly. I need to removed duplicated Entrez ID's in my target data frame. 
```

```{r}
#Remove duplicate EntrezID
edata_kosin = edata_kosin[!duplicated(edata_kosin$ENTREZID),]

#Merge Data frames. 
edata_kosin = merge(annotatedkosin, edata_kosin, by.x="ENTREZID")
dim(edata_kosin)
dim(annotatedkosin)
```
```{r}
#Remove columns 
edata_kosin = dplyr::select(edata_kosin, -c("ENTREZID","ENSEMBL"))
```

## Check for NA in SYMBOL
```{r}
table(is.na(edata_kosin$SYMBOL))
# There is NA due to Entrez Ids that no longer map to gene symbols. 
```


```{r}
#Remove NA Symbols
edata_kosin = edata_kosin[!is.na(edata_kosin$SYMBOL),]
```
## Check for duplicates
```{r}
table(duplicated(edata_kosin$SYMBOL))
```
```{r}
#Aggregate duplicate genes by mean
edata_kosin %>% group_by(SYMBOL) %>% summarise_all(mean) %>% data.frame() -> edata_mergedkosin
edata_kosin = edata_mergedkosin
 #Aggregate and mean duplicate ENTREZIDs 
```

#Check for NA in dataset
```{r}
table(is.na(edata_kosin))
```
```{r}
which(is.na(edata_kosin), arr.ind=TRUE)
```

#Impute NA
```{r}
edata_kosin = edata_kosin %>% tibble::column_to_rownames("SYMBOL") # Make the first column the row name
edata_kosin = as.matrix(edata_kosin)
imputekosin = impute.knn(edata_kosin, k=10, rowmax = 0.2, colmax = 0.2) #KNN imputation with no more than 20% missingness allowed. 
edata_kosin = imputekosin$data 
```

```{r}
#Confirm no NA
table(is.na(edata_kosin))
```


#Exploratory data analysis 

Boxplot
```{r}
# Look at data that is not transformed vs transformed
par(mfrow=c(1,2))
boxplot(edata_kosin, col=2, range=0)
boxplot(log2(edata_kosin+1), col=2, range=0)
#Clearly data was already transformed 
```
Histogram
```{r}
par(mfrow=c(1,1))
hist(edata_kosin[,1],col=2)

```
Density Plot
```{r}
par(mfrow=c(1,1))
plot(density(edata_kosin[,1]),col=2, ylim = c(0,0.85))
lines(density(edata_kosin[,2]),col=3)
```
qqPlot
```{r}
qqplot(edata_kosin[,1], edata_kosin[,2],col=3)
```
Bland Altman Plot
```{r}
# Bland Altman Plot
mm = edata_kosin[,1] - edata_kosin[,2]
aa = edata_kosin[,1] + edata_kosin[,2]
plot(aa,mm,col=2) 
```

#Remove low expression genes 
```{r}
mediankosin = rowMedians(as.matrix(edata_kosin))
hist(mediankosin, breaks = 200)
#Can see clear peak 
```
```{r}
hist(mediankosin, breaks = 400, xlim = c(5,7))
abline(v=6.02, lwd=3)
#Zoom into data and determine cut-off point
```
```{r}
#Remove low expression genes
mediankosin = as.data.frame(mediankosin)
mediankosin = mediankosin > 6.02
edata_kosin = edata_kosin[mediankosin,]
```


#Quantile Normalization 

```{r}
#Check if quantile normalization is required.
colramp = colorRampPalette(c(3,"white",2))(20)
plot(density(edata_kosin[,1]),col=colramp[1],lwd=1,ylim=c(0,.75))
for(i in 2:109){lines(density(edata_kosin[,i]),lwd=1,col=colramp[i])}
#There is some larger variability in this cohort. I will quantile normalize. GEO does not mention if data has been quantile normalized. 
```

#Quantile normalization
```{r}
#Quantile normalize
norm_kosin = normalize.quantiles(as.matrix(edata_kosin))
```

```{r}
#Check normalize data plot
plot(density(norm_kosin[,1]),col=colramp[1],lwd=1,ylim=c(0,.75))
for(i in 2:109){lines(density(norm_kosin[,i]),lwd=1,col=colramp[i])}
```

```{r}
x = colnames(edata_kosin)
colnames(norm_kosin) = x
y = row.names(edata_kosin)
row.names(norm_kosin) = y
```




