---
title: "TCGA Subtyping"
author: "Daniel Skubleny"
date: "16/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#FSQN function 
```{r}
quantileNormalizeByFeature <- function(matrix_to_normalize,
                                       target_distribution_matrix){

    if (ncol(matrix_to_normalize) != ncol(target_distribution_matrix)){
        cat("ERROR: Data matrices are not compatible - column lengths differ!")
    }
    else{

        data.qn <- matrix(0, nrow = nrow(matrix_to_normalize),
                          ncol = ncol(matrix_to_normalize))

        for (i in 1:ncol(matrix_to_normalize)){
            feature.to.normalize <- matrix_to_normalize[,i]
            target.feature.dist <- target_distribution_matrix[,i]
            result <- normalize.quantiles.use.target(
                x = as.matrix(feature.to.normalize),
                target = target.feature.dist,
                copy = TRUE)
            data.qn[,i] <- result
        }
        rownames(data.qn) = rownames(matrix_to_normalize)
        colnames(data.qn) = colnames(matrix_to_normalize)
        return(data.qn)
    }
}
```

#Normalization with housekeeping genes

```{r}
housekeeping_genes = c("ACTB", "CTCF", "EIF4G", "HNRNPK", "RPL9", "SUMO3", "XRCC5")
normalizergenes = c(TCGAfinalgenes,housekeeping_genes)
```

```{r}
#Data sets - reduce to commongenes and transpose for FSQN

#TCGA normalization distribution
tcganormalizer <- subset(edata_TCGA, rownames(edata_TCGA) %in% as.matrix(normalizergenes))
tcganormalizer = t(tcganormalizer)

#ACRG
log_ACRG_cancer <- subset(log_ACRG, rownames(log_ACRG) %in% as.matrix(normalizergenes))
log_ACRG_cancer = t(log_ACRG_cancer)

#TCGA
fullTCGA_cancer <- subset(log_edata_fullTCGA, rownames(log_edata_fullTCGA) %in% as.matrix(normalizergenes))
fullTCGA_cancer = t(fullTCGA_cancer)

#Singapore 
cancer_sing <- subset(edata_sing, rownames(edata_sing) %in% as.matrix(normalizergenes))
cancer_sing = t(cancer_sing)

#Singapore batch B 
cancer_batchb <- subset(edata_batchb, rownames(edata_batchb) %in% as.matrix(normalizergenes))
cancer_batchb = t(cancer_batchb)

#Samsung 
cancer_SMC <- subset(edata_SMC, rownames(edata_SMC) %in% as.matrix(normalizergenes))
cancer_SMC = t(cancer_SMC)

#Shanghai
cancer_shanghai <- subset(edata_shanghai, rownames(edata_shanghai) %in% as.matrix(normalizergenes))
cancer_shanghai = t(cancer_shanghai)

#Yonsei
cancer_yonsei <- subset(edata_yonsei, rownames(edata_yonsei) %in% as.matrix(normalizergenes))
cancer_yonsei = t(cancer_yonsei)

#MDACC
cancer_MDACC <- subset(edata_MDACC, rownames(edata_MDACC) %in% as.matrix(normalizergenes))
cancer_MDACC = t(cancer_MDACC)

#KUGH
cancer_KUGH <- subset(edata_KUGH, rownames(edata_KUGH) %in% as.matrix(normalizergenes))
cancer_KUGH = t(cancer_KUGH)

#Kosin
cancer_kosin <- subset(edata_kosin, rownames(edata_kosin) %in% as.matrix(normalizergenes))
cancer_kosin = t(cancer_kosin)

#Yonsei MDACC
cancer_yonseiMDACC <- subset(edata_yonseiMDACC, rownames(edata_yonseiMDACC) %in% as.matrix(normalizergenes))
cancer_yonseiMDACC = t(cancer_yonseiMDACC)
```


```{r}
#Fix the patient_id string

fullTCGA_cancer = tibble::rownames_to_column(as.data.frame(fullTCGA_cancer), "patient_id")

patient_id = substr(fullTCGA_cancer$patient_id,1,nchar(fullTCGA_cancer$patient_id)-3)
patient_id = gsub("\\.", "-", patient_id)
fullTCGA_cancer$patient_id = patient_id
fullTCGA_cancer = tibble::column_to_rownames(fullTCGA_cancer,"patient_id")
fullTCGA_cancer = as.matrix(fullTCGA_cancer)
```

#FSQN the cancers
```{r}
#TCGA FSQN to ACRG as reference due to predominate data derived from affymetrix platform and that TME clusters were established ACRG.
set.seed(99)
target = as.matrix(tcganormalizer)
test = as.matrix(log_ACRG_cancer)
fsqn_cancer_ACRG = quantileNormalizeByFeature(test, target)
```

```{r}
#FSQN for remaining datasets
set.seed(99)
target = as.matrix(tcganormalizer)
test = as.matrix(cancer_sing)
fsqn_cancer_sing = quantileNormalizeByFeature(test, target)

test = as.matrix(fullTCGA_cancer)
fsqn_cancer_TCGA = quantileNormalizeByFeature(test, target)

test = as.matrix(cancer_batchb)
fsqn_cancer_batchb = quantileNormalizeByFeature(test, target)

test = as.matrix(cancer_SMC)
fsqn_cancer_SMC = quantileNormalizeByFeature(test, target)

test = as.matrix(cancer_shanghai)
fsqn_cancer_shanghai = quantileNormalizeByFeature(test, target)

test = as.matrix(cancer_yonsei)
fsqn_cancer_yonsei = quantileNormalizeByFeature(test, target)

test = as.matrix(cancer_MDACC)
fsqn_cancer_MDACC = quantileNormalizeByFeature(test, target)

test = as.matrix(cancer_KUGH)
fsqn_cancer_KUGH = quantileNormalizeByFeature(test, target)

test = as.matrix(cancer_kosin)
fsqn_cancer_kosin = quantileNormalizeByFeature(test, target)

test = as.matrix(cancer_yonseiMDACC)
fsqn_cancer_yonseiMDACC = quantileNormalizeByFeature(test, target)
```

```{r}
#Combine into full dataframe with all patients 
classify_TCGA = rbind(fsqn_cancer_ACRG, fsqn_cancer_TCGA)
classify_TCGA = rbind(classify_TCGA, fsqn_cancer_sing)
classify_TCGA = rbind(classify_TCGA, fsqn_cancer_batchb)
classify_TCGA = rbind(classify_TCGA, fsqn_cancer_SMC)
classify_TCGA = rbind(classify_TCGA, fsqn_cancer_shanghai)
classify_TCGA = rbind(classify_TCGA, fsqn_cancer_yonsei)
classify_TCGA = rbind(classify_TCGA, fsqn_cancer_MDACC)
classify_TCGA = rbind(classify_TCGA, fsqn_cancer_KUGH)
classify_TCGA = rbind(classify_TCGA, fsqn_cancer_kosin)
classify_TCGA = rbind(classify_TCGA, fsqn_cancer_yonseiMDACC)
```
```{r}
classify_TCGA <- classify_TCGA[, TCGAfinalgenes]
```
#Classify the cancers according to TCGA 
```{r}
predict.classify_TCGA = predict(TCGA.finalmodel,classify_TCGA)
predict.classify_TCGA_prob = predict(TCGA.finalmodel,classify_TCGA, type = "prob")

table(predict.classify_TCGA)
```
```{r}
#Change the subtype data to match the strings in the survival data
TCGA_subtype = as.data.frame(row.names(classify_TCGA))
TCGA_subtype$TCGA_subtype = predict.classify_TCGA
colnames(TCGA_subtype)[which(names(TCGA_subtype) == "row.names(classify_TCGA)")] <- "patient_id"
```

#Create dataframe with subtpyes as probability. 
Note if survival_TCGA is required it is available as a csv in the data folder.
```{r}
classify_TCGA_prob = tibble::rownames_to_column(predict.classify_TCGA_prob, "patient_id")
TCGA_probability = merge(TCGA_subtype,survival_TCGA, by.x="patient_id")
TCGA_probability = merge(TCGA_probability,classify_TCGA_prob, by.x="patient_id")
TCGA_probability$OS_time = as.numeric(TCGA_probability$OS_time)
TCGA_probability$OS_status = as.numeric(TCGA_probability$OS_status)
TCGA_probability$age = as.numeric(TCGA_probability$age)

TCGA_probability$TCGA_subtype = as.factor(TCGA_probability$TCGA_subtype)
```
```{r}
write.csv(TCGA_probability, "TCGA_probability.csv")
```
